#Descarhar una version del alpine con un openjdk 17 que es la misma vesion del spring boot 
FROM openjdk:17-jdk-alpine
#copiar el archivo donde se empaqueta la aplicasion despues de ejecutar mvn clean package y el segundo argumento
#el nombre del archivo dentro del docker 
COPY target/App_gestion-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "app.jar" ]