name: publish

on:
  push:
    branches: ["main"]


jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          maven-version: '3.8.4'
      - name: Build with Maven
        run: |
          cd "./Back end/App_gestion"  # Cambia al directorio del proyecto
          mvn clean package

      - name: Login to GitHub Container Register
        uses: docker/Login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.TOKEN_CD}}
      
      - name: Build image
        run: |
            docker build -t ghcr.io/alejandrodiazvera/app-gestion-integral:latest "./Back end/App_gestion"
            # docker build ./Back end\App_gestion --tag ghcr.io/alejandrodiazvera/app-gestion-integral:latest
            docker push ghcr.io/alejandrodiazvera/app-gestion-integral:latest

            
            
       