name: publish

on:
  push:
    branches: ["main"]


jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          maven-version: '3.8.4'
      - name: Build with Maven
        run: |
          cd "./Back end/App_gestion" 
          mvn clean package

      - name: Login to GitHub Container Register
        uses: docker/Login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.TOKEN_CD}}
      
      - name: Build image
        run: |
            docker build -t ghcr.io/alejandrodiazvera/app-gestion-integral:latest "./Back end/App_gestion"
            docker push ghcr.io/alejandrodiazvera/app-gestion-integral:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Conectar al vps and Iniciar docker
        run: |
            sshpass -p ${{ secrets.SSH_PAS}} ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER_IP}} << EOF
            docker login ghcr.io -u alejandrodiazvera -p ${{ secrets.TOKEN_CD}}
            docker pull ghcr.io/alejandrodiazvera/app-gestion-integral:latest
            # Verificar si el contenedor 'app-gest' existe
            if docker ps -a --format '{{.Names}}' | grep -q "app-gest"; then
                docker stop app-gest
                docker rm app-gest
            else
                echo "El contenedor 'app-gest' no existe"
            fi
        
            # Eliminar la imagen si existe
            if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "ghcr.io/alejandrodiazvera/app-gestion-integral:latest"; then
                docker rmi ghcr.io/alejandrodiazvera/app-gestion-integral
            fi
        
            # Ejecutar el nuevo contenedor
            docker run -d \
                -p 8080:8080 \
                --restart always \
                --name app-gest \
                ghcr.io/alejandrodiazvera/app-gestion-integral
        
            EOF

            
       